version: '3'
services:
  db:
    image: postgres:15
    container_name: cars-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
