# Generated by Django 5.0.6 on 2024-05-27 18:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("daily_price_in_dollars", models.IntegerField()),
                ("number_of_seats", models.IntegerField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("electro", "Electro"), ("petrol", "Petrol")],
                        max_length=10,
                    ),
                ),
                ("initial_deposit_in_dollars", models.IntegerField()),
                (
                    "transmission_type",
                    models.CharField(
                        choices=[("automatic", "Automatic"), ("manual", "Manual")],
                        max_length=10,
                    ),
                ),
                (
                    "fines",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("renting_period_in_days", models.IntegerField()),
                ("rent_to", models.DateTimeField(blank=True, null=True)),
                ("image_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "current_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
