# Generated by Django 5.0.6 on 2024-05-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image_url",
            field=models.TextField(blank=True),
        ),
    ]
