# Generated by Django 5.0.6 on 2024-05-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rent", "0004_historicalrecord_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalrecord",
            name="is_finished_on_time",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalrecord",
            name="renting_period_in_days",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
